GET http://localhost/grade-book-v2/api/index.php/user/list?role=0

###

POST http://localhost/grade-book-v2/api/index.php/auth/login HTTP/1.1
content-type: application/json

{
    "email": "q@qq",
    "password": "qwerty",
    "sessionId": "ce6lv5j0ldkdn1o5s1a493r5jc"
}

###

GET http://localhost/grade-book-v2/api/index.php/auth/status

###

DELETE http://localhost/grade-book-v2/api/index.php/auth/logout

###

GET http://localhost/grade-book-v2/api/index.php/grade/list?course=4

###

DELETE http://localhost:80/grade-book-v2/api/index.php/user/delete?id=2

###

POST http://localhost/grade-book-v2/api/index.php/user/add HTTP/1.1
content-type: application/json

{
    "fullname": "aaaa aa",
    "email": "a.a@a",
    "password": "qwerty",
    "role": 1
}

###

PATCH http://localhost/grade-book-v2/index.php/user/edit?id=19 HTTP/1.1
content-type: application/json

{
    "fullname": "Qwerty1"
}

###

GET http://localhost/grade-book-v2/api/index.php/course/list
